// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvieytrqzxuvtxrauych.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aWV5dHJxenh1dnR4cmF1eWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjk4MzksImV4cCI6MjA2OTY0NTgzOX0.250YfbMBk21mtQWaBcpq8BgZVG6LLgLdyR_cRH39Wm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});